"""Report models for Galvaniy Labs."""

from pydantic import BaseModel, Field
from typing import Optional, List, Any
from datetime import datetime


class ReportGenerateRequest(BaseModel):
    """Request to generate a lab report."""

    experiment_code: str = Field(..., min_length=1, max_length=50, description="Experiment code, e.g. A-2, B-6")


class ReportTable(BaseModel):
    """A data table within a report."""

    title: Optional[str] = None
    headers: List[str]
    rows: List[List[str]]


class ReportGraphConfig(BaseModel):
    """Graph configuration within a report."""

    table_index: int = Field(alias="tableIndex", default=0)
    x_column_index: int = Field(alias="xColumnIndex", default=0)
    y_column_index: int = Field(alias="yColumnIndex", default=1)
    title: str = ""

    class Config:
        populate_by_name = True


class ReportContent(BaseModel):
    """Full report content generated by AI."""

    title: str = ""
    date: str = ""
    partners: str = ""
    objectives: List[str] = []
    apparatus: List[str] = []
    theory: str = ""
    procedure: List[str] = []
    precautions: List[str] = []
    discussion: str = ""
    sources_of_error: List[str] = Field(default=[], alias="sourcesOfError")
    conclusion: str = ""
    references: List[str] = []
    questions: List[Any] = []
    tables: List[Any] = []
    calculation_script: str = Field(default="", alias="calculationScript")
    analysis_template: str = Field(default="", alias="analysisTemplate")
    graph_config: Optional[Any] = Field(default=None, alias="graphConfig")
    simulation_script: str = Field(default="", alias="simulationScript")
    controls: List[Any] = []

    class Config:
        populate_by_name = True


class Report(BaseModel):
    """A saved report."""

    id: str
    experiment_code: str = Field(alias="experimentCode", default="")
    date: str = ""
    content: str = ""  # JSON string of ReportContent
    user_uid: str = ""  # Owner user UID

    class Config:
        populate_by_name = True


class ReportResponse(BaseModel):
    """Report returned to client."""

    id: str
    experiment_code: str
    date: str
    content: str  # JSON string of the report data
